pipeline {
	
	agent none
	triggers { pollSCM('H/2 * * * *') }
	
	stages {
		stage('Install') {
			agent {
				docker {
					label 'docker'
					image 'python:2.7.18-slim'					
				}
			}
			steps {
				echo "Installing"
				dir('vote') {
					sh "pip install -r requirements.txt"
				}
			}
		}
		stage('Tests') {
			agent {
				docker {
					label 'docker'
					image 'python:2.7.18-slim'					
				}
			}
			steps {
				echo "Testing"
				dir('vote') {
					sh "nosetests -v"
				}
			}
		}
		stage('Package-docker') {
			agent {
				label 'docker'
			}
			steps {
				echo "Packaging into Docker"
				script {
					docker.withRegistry('https://192-168-18-58.nip.io/repository/docker/', 'nexus-registry') {
						def customImage = docker.build("repository/docker/instavote-vote:${env.BUILD_ID}", "./vote")
						customImage.push()
						customImage.push("${GIT_BRANCH}")
					}
				}
			}
		}
	}
	post {
		success {
			echo "Pipeline executed successfully"
		}
	}

}
