pipeline {
    triggers { pollSCM('H/2 * * * *') }
    agent {
        docker {
            image 'python:2.7.18-alpine3.11'
            label 'docker'
        }
    }
    stages {
        when { changeset "vote/tests/*.py" }
        stage('Install')
        {
            steps {
                echo "Install"
                dir('vote')
                {
                    sh "pip install -r requirements.txt"
                }              
            }
        }
        stage('Tests')
        {
            when { changeset "vote/tests/*.py" }
            steps {
                echo "Tests"
                dir('vote')
                {
                    sh "nosetests -v"
                }
                echo "Branch: ${GIT_BRANCH}"
            }
        }
    }
}
