pipeline {
	
	agent none
	triggers { pollSCM('H/2 * * * *') }
	
	stages {
		stage('Compile') {
			when { 
				changeset "worker/**" 
			}
			agent {
				docker {
					label 'docker'
					image 'maven:3.6.1-jdk-8-alpine'					
				}
			}
			steps {
				echo "Compiling"
				dir('worker') {
					sh "mvn compile"
				}
			}
		}
		stage('Tests') {
			when { 
				changeset "worker/**" 
			}
			agent {
				docker {
					label 'docker'
					image 'maven:3.6.1-jdk-8-alpine'					
				}
			}
			steps {
				echo "Testing"
				dir('worker') {
					sh "mvn test"
				}
			}
		}
		stage('Package') {
			when { 
				changeset "worker/**" 
			}
			agent {
				docker {
					label 'docker'
					image 'maven:3.6.1-jdk-8-alpine'					
				}
			}
			steps {
				echo "Packaging"
				dir('worker') {
					sh "mvn package -DskipTests"
				}
			}
		}
		stage('Package-docker') {
			when {
				branch 'master'
				changeset "worker/**"
			}
			agent {
				label 'docker'
			}
			steps {
				echo "Packaging into Docker"
				script {
					docker.withRegistry('https://192-168-18-58.nip.io/repository/docker/', 'nexus-registry') {
						def customImage = docker.build("repository/docker/instavote-worker:${env.BUILD_ID}", "./worker")
						customImage.push()
						customImage.push("${GIT_BRANCH}")
					}
				}
			}
		}
	}
	post {
		success {
			echo "Pipeline executed successfully"
		}
	}

}
