pipeline {
	
	agent none
	triggers { pollSCM('H/2 * * * *') }
	
	stages {
		stage('Compile') {
			when { 
				changeset "**/worker/**" 
			}
			agent {
				docker {
					label 'docker'
					image 'maven:3.6.1-jdk-8-alpine'					
				}
			}
			steps {
				dir('worker') {
					sh "mvn compile"
				}
			}
		}
		stage('Tests') {
			when { 
				changeset "**/worker/**" 
			}
			agent {
				docker {
					label 'docker'
					image 'maven:3.6.1-jdk-8-alpine'					
				}
			}
			steps {
				dir('worker') {
					sh "mvn tests"
				}
			}
		}
		stage('Package') {
			when { 
				changeset "**/worker/**" 
			}
			agent {
				docker {
					label 'docker'
					image 'maven:3.6.1-jdk-8-alpine'					
				}
			}
			steps {
				dir('worker') {
					sh "mvn package -DskipTests"
				}
			}
		}
	}
	post {
		success {
			echo "Pipeline executed successfully"
		}
	}

}
